### ISSUE TITLE
http 500 for /gwc/documents

### ISSUE THREAD

**Issue by ccsmart** [gawati/gawati-editor-ui#11]
https://data.dev.gawati.org/gwc/documents
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Snippet from apache config:

  <Location ~ "/gwc/(.*)">
    AddType text/cache-manifest .appcache
    ProxyPassMatch "http://localhost:9102/gwc/$1"
    ProxyPassReverse "http://localhost:9102/gwc/$1"
    SetEnv force-proxy-request-1.0 1
    SetEnv proxy-nokeepalive 1
  </Location>

[root@alldev portal]# netstat -lnp | grep 9102
tcp        0      0 127.0.0.1:9102          0.0.0.0:*               LISTEN      7223/node

[root@alldev portal]# ps -eo pid,uid,args | grep 7223
 7223  1008 /usr/bin/node ./bin/www

[root@alldev portal]# grep 1008 /etc/passwd
gawatidevclientsrv:x:1008:1008::/home/gawatidevclientsrv:/bin/bash

access.log:
109.164.203.165 - - [13/Apr/2018:11:35:42 +0200] "POST /gwc/documents HTTP/1.1" 500 1000 "https://data.dev.gawati.org/_lang/en/dashboard" "Mozilla/5.0 (Windows
NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

syslog:
Apr 13 11:35:42 alldev node: IN: receiveSubmitData
Apr 13 11:35:42 alldev node: IN: convertAknXmlToObjects

**Comment by ccsmart** [comment]
POST /gwc/documents HTTP/1.0
Host: localhost:9102
Accept: application/json, text/plain, */*
Origin: https://data.dev.gawati.org
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: https://data.dev.gawati.org/_lang/en/dashboard
Accept-Encoding: gzip, deflate, br
Accept-Language: en,en-US;q=0.9,de-DE;q=0.8,de;q=0.7
X-Forwarded-For: 109.164.203.165
X-Forwarded-Host: data.dev.gawati.org
X-Forwarded-Server: data.dev.gawati.org
Content-Length: 55

{"data":{"docTypes":"all","itemsFrom":1,"pageSize":10}}

HTTP/1.1 500 Internal Server Error
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 1000
ETag: W/"3e8-5dDyaoyELS0+FksFZ7cXFwMvo3Y"
Date: Fri, 13 Apr 2018 09:54:46 GMT
Connection: close

<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <link rel='stylesheet' href='/stylesheets/style.css' />
  </head>
  <body>
    <h1>Cannot read property &#x27;akomaNtoso&#x27; of undefined</h1>
<h2></h2>
<pre>TypeError: Cannot read property &#x27;akomaNtoso&#x27; of undefined
    at getOnlineDocumentFromAknObject (/home/gawatidevclientsrv/portal/documentmanage.js:361:53)
    at packages.map (/home/gawatidevclientsrv/portal/documentmanage.js:403:24)
    at Array.map (&lt;anonymous&gt;)
    at convertAknXmlToObjects (/home/gawatidevclientsrv/portal/documentmanage.js:402:31)
    at Layer.handle [as handle_request] (/home/gawatidevclientsrv/portal/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gawatidevclientsrv/portal/node_modules/express/lib/router/route.js:137:13)
    at axios.then.catch (/home/gawatidevclientsrv/portal/documentmanage.js:429:13)
    at &lt;anonymous&gt;
    at process._tickCallback (internal/process/next_tick.js:188:7)</pre>

  </body>
</html>

**Comment by kohsah** [comment]
@ccsmart  i think it throws an error becasue there are no documents .. .will check.

**Comment by ccsmart** [comment]
postinstaller currently introduces a chicken and egg problem such that docuemnts can not be preloaded correctly. suggested solution is to have the pstinstaller itself create the basic data template
